name:                haskell-loki
version:             0.1.0.0
github:              "githubuser/haskell-loki"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-loki#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


library:
  source-dirs: src
  dependencies:
    - deepseq
    - colourista
    - effectful
    - effectful-core
    - monad-time-effectful
    - log-base
    - log-effectful
    - lucid-aria
    - Unique
    - aeson
    - monad-time
    - wai-log
    - aeson-qq
    - async
    - base
    - base64
    - cache >= 0.1.3.0
    - case-insensitive
    - clock
    - co-log
    - co-log-core
    - containers
    - safe-exceptions
    - cryptonite
    - bytestring
    - data-default
    - deriving-aeson
    - dotenv
    - envy
    - errors
    - wai-extra
    - extra
    - fmt
    - generic-lens
    - hspec
    - http-api-data
    - lens
    - lens-aeson
    - megaparsec
    - optics-core
    - mtl
    - safe
    - optics-th

    - random
    - relude >= 1.2.0.0
    - resource-pool
    - resourcet
    - scientific
    - http-types
    - servant
    - text
    - text-conversions
    - text-display
    - time
    - transformers
    - transformers-except
    - unordered-containers
    - valor >= 1.0.0.0
    - vector
    - wai
    - warp
    - witch
    - wreq
    - xxhash
    - template-haskell
    - yaml
    - pretty-relative-time
    - neat-interpolation
    - PyF
    - pretty-simple
    - directory
    - network-uri
    - hspec-expectations-json
    - text-time

executables:
  haskell-loki-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-loki

tests:
  haskell-loki-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-loki
